version: '3.4'

services:
  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/var/www/html
        - ./site.conf:/etc/nginx/conf.d/default.conf
        # - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./code:/var/www/html