version: '3.4'

services:
  web:
    build: 
      context: .
      dockerfile: ./config/NGINX_Dockerfile
    ports:
        - "8080:80"
    # volumes:
        # - ./code/:/var/www/html
    #     - ./site.conf:/etc/nginx/conf.d/default.conf
        # - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php-fpm
  php-fpm:
    build: 
      context: .
      dockerfile: ./config/PHP_Dockerfile
    volumes:
      - ./logs/xdebug:/logs/xdebug
      - ./logs/php-fpm/:/tmp/xdebug_log
      - ./config/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini 
      # - .:/var/www/html